#parameters:
#    entity_manager:  doctrine.orm.entity_manager

services:
    image.manager:
        class:        Bundles\WidgetBundle\Service\ImageService
        arguments:
            EntityManager: "@doctrine.orm.entity_manager"
            fontPath: @=service('kernel').locateResource('@WidgetBundle/Resources/public/fonts/arial.ttf')